### ISSUE TITLE
Warning babel preset

### ISSUE THREAD

**Issue by jacekelgda** [jacekelgda/vacation-status-update#102]
Two warnings popped up while `yarn install`

<img width="1250" alt="screen shot 2017-10-10 at 19 55 01" src="https://user-images.githubusercontent.com/1003372/31402031-fc922a60-adf4-11e7-8c4b-3f66a57252a1.png">

```warning babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
warning crypto@0.0.3: This package is no longer supported. It's now a built-in Node module. If you've depended on crypto, you should switch to the one that's built-in.```

**Comment by SmirnovW** [comment]
@jacekelgda Hi there, I've just installed your project and I didn't get any warnings :(

**Comment by jacekelgda** [comment]
@SmirnovW Thanks for looking into that. Seems you are right, the issue has gone away after last PRs. Sorry to waste your time with this!
