### ISSUE TITLE
Ask if user X is OOO today

### ISSUE THREAD

**Issue by RafalWilinski** [jacekelgda/vacation-status-update#94]
It would be nice if bot could respond to requests like:

```
Is @rwilinski ooo today?
- Yes, he/she is. He/she'll be back in X days.

Is Rafal Wilinski off?
- No, she/he is not.
```

**Comment by jacekelgda** [comment]
When someone is on vacation, they have a special `presence` status set up `OOO until 12th of August` for example + special emoji. So, when you are mentioning someone in a message you already see his/her status and automatically are aware of vacation.

That being said, adding this functionality will just make bot more aware and smarter. Wouldn't put it on the top of priorities though.
